# Generated by Django 3.2.3 on 2023-11-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificacionAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionusuario',
            name='calificacion',
            field=models.FloatField(),
        ),
    ]
