version: '2.1'
services:
  mysql_db:
    image: mysql:5.7
    environment:   # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: apparkcar
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    networks:
      - app-tier
  ms-apparkcar-usuario:
    build: .
    depends_on:
            - migrations
            - mysql_db
    volumes:
        - .:/apparkcar
    networks:
      - app-tier
    ports:
      - "8000:8000"
    command: python /apparkcar/apparkcar/API_usuario/manage.py runserver 127.0.0.1:8000

  migrations:
    build: .
    volumes:
      - .:/apparkcar
    depends_on:
        mysql_db:
                 condition: service_healthy
    networks:
      - app-tier
    command: python /apparkcar/apparkcar/API_usuario/manage.py makemigrations --noinput &&
             python /apparkcar/apparkcar/API_usuario/manage.py migrate &&
             python /apparkcar/apparkcar/API_estacionamientos/manage.py makemigrations --noinput &&
             python /apparkcar/apparkcar/API_estacionamientos/manage.py migrate &&
             python /apparkcar/apparkcar/API_calificacion/manage.py makemigrations --noinput &&
             python /apparkcar/apparkcar/API_calificacion/manage.py migrate


  ms-apparkcar-calificacion:
      build: .
      depends_on:
              - migrations
              - mysql_db
      volumes:
          - .:/apparkcar
      networks:
        - app-tier
      ports:
        - "8001:8001"
      command: python /apparkcar/apparkcar/API_calificacion/manage.py runserver 127.0.0.1:8001

  ms-apparkcar-estacionamiento:
    build: .
    depends_on:
            - migrations
            - mysql_db
    volumes:
        - .:/apparkcar
    networks:
      - app-tier
    ports:
      - "8002:8002"
    command: python /apparkcar/apparkcar/API_estacionamientos/manage.py runserver 127.0.0.1:8002
ms-apparkcar-reservas:
    build: .
    depends_on:
            - migrations
            - mysql_db
    volumes:
        - .:/apparkcar
    networks:
      - app-tier
    ports:
      - "8003:8003"
    command: python /apparkcar/apparkcar/API_reservas/manage.py runserver 127.0.0.1:8003


networks:
  app-tier:
    driver: bridge

