# Generated by Django 3.2.3 on 2023-11-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('nombre', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('email', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('ApPaterno', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('ApMaterno', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('password', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='duenno',
            fields=[
                ('nombre', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('email', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('ApPaterno', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('ApMaterno', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('password', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('id_duenno', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'duennos',
            },
        ),
    ]
