# Generated by Django 3.2.3 on 2023-11-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAPP', '0003_auto_20231118_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
