# Generated by Django 3.2.3 on 2023-11-22 16:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAPP', '0004_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
