# Generated by Django 3.2.3 on 2023-11-24 18:28

from django.db import migrations, models
import usuarioAPP.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAPP', '0007_usuario_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to=usuarioAPP.models.generate_filename),
        ),
    ]
