# Generated by Django 3.2.3 on 2023-11-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamientoAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='url',
        ),
        migrations.AddField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(default='default_image.jpg', upload_to='imagenes_estacionamiento/'),
        ),
    ]
