# Generated by Django 3.2.3 on 2023-12-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamientoAPP', '0002_auto_20231130_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamiento',
            name='direccion',
        ),
    ]
