# Generated by Django 4.1.5 on 2023-10-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calificacionUsuario',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('id_calificado', models.IntegerField()),
                ('calificacion', models.IntegerField()),
                ('comentario', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'calificacion',
            },
        ),
    ]
